import { Component, effect, inject, OnInit, signal } from '@angular/core';
import { TranslocoDirective } from '@jsverse/transloco';
import { TableModule } from 'primeng/table';
import { NgForOf, NgOptimizedImage } from '@angular/common';
import { DataViewModule } from 'primeng/dataview';
import { FullPackageDefinition, StatefulPackage } from '../interfaces';
import { ChildProcess, Command } from '@tauri-apps/plugin-shell';
import { Card } from 'primeng/card';
import { flavors } from '@catppuccin/palette';
import { TabsModule } from 'primeng/tabs';
import { Tooltip } from 'primeng/tooltip';
import { OperationManagerService } from '../operation-manager/operation-manager.service';
import { LoadingService } from '../loading-indicator/loading-indicator.service';
import { Logger } from '../logging/logging';
import { ConfigService } from '../config/config.service';

@Component({
  selector: 'rani-gaming',
  imports: [TranslocoDirective, TableModule, DataViewModule, NgForOf, Card, NgOptimizedImage, TabsModule, Tooltip],
  templateUrl: './gaming.component.html',
  styleUrl: './gaming.component.css',
})
export class GamingComponent implements OnInit {
  backgroundColor = signal<string>('background-color');
  tabIndex = signal<number>(0);

  data: { name: string; sections: FullPackageDefinition[] }[] = [
    {
      name: 'gaming.launchers',
      sections: [
        { name: 'Bottles', pkgname: ['bottles'], icon: 'bottles.svg' },
        { name: 'GameHub', pkgname: ['gamehub'], icon: 'gamehub.svg' },
        { name: 'Heroic Games Launcher', pkgname: ['heroic-games-launcher'], icon: 'heroic-icon.png' },
        { name: 'Itch', pkgname: ['itch'], icon: 'itch.svg' },
        { name: 'Lutris', pkgname: ['lutris'], icon: 'lutris.png' },
        { name: 'Minigalaxy', pkgname: ['minigalaxy'], icon: 'minigalaxy.png' },
        { name: 'Steam (native)', pkgname: ['steam-native-runtime'], icon: 'steam.png' },
        { name: 'Steam (runtime)', pkgname: ['steam'], icon: 'steam.png' },
      ],
    },
    {
      name: 'gaming.wine',
      sections: [
        { name: 'Boxtron', pkgname: ['boxtron'], icon: 'DOSBox.png' },
        { name: 'Luxtorpeda', pkgname: ['luxtorpeda'], icon: 'proton.svg' },
        { name: 'ProtonGE-Custom', pkgname: ['proton-ge-custom-bin'], icon: 'proton-ge-custom.png' },
        { name: 'Protontricks', pkgname: ['protontricks'], icon: 'proton.svg' },
        { name: 'WINE', pkgname: ['wine-meta'], icon: 'winehq.png' },
        { name: 'Winetricks', pkgname: ['winetricks'], icon: 'winehq.png' },
      ],
    },
    {
      name: 'gaming.tools',
      sections: [
        { name: 'DXVK', pkgname: ['dxvk-mingw-git'], icon: 'generic.png' },
        { name: 'Gamemode', pkgname: ['gamemode', 'lib32-gamemode'], icon: 'generic.png' },
        { name: 'Gamescope session (Steam)', pkgname: ['gamescope-session-steam-git'], icon: 'steam.png' },
        { name: 'Gamescope session', pkgname: ['gamescope-session-git'], icon: 'valve.png' },
        { name: 'Gamescope', pkgname: ['gamescope'], icon: 'valve.png' },
        { name: 'LACT', pkgname: ['lact'], icon: 'lact.png' },
        { name: 'MangoHud', pkgname: ['mangohud', 'lib32-mangohud'], icon: 'mangohud.png' },
        { name: 'SteamTinkerLaunch', pkgname: ['steamtinkerlaunch'], icon: 'steam.png' },
        { name: 'VR video player', pkgname: ['vr-video-player'], icon: 'generic.png' },
        { name: 'vkBasalt', pkgname: ['vkbasalt'], icon: 'generic.png' },
      ],
    },
    {
      name: 'gaming.misc',
      sections: [
        { name: 'AntimicroX', pkgname: ['antimicrox'], icon: 'antimicrox.png' },
        { name: 'AnyDesk', pkgname: ['anydesk'], icon: 'anydesk.svg' },
        { name: 'CoreCtrl', pkgname: ['corectrl'], icon: 'corectrl.png' },
        { name: 'Discord', pkgname: ['discord'], icon: 'discord.png' },
        { name: 'DisplayCAL', pkgname: ['displaycal'], icon: 'displaycal.png' },
        { name: 'DroidCam', pkgname: ['droidcam'], icon: 'droidcam.png' },
        { name: 'EasyEffects', pkgname: ['easyeffects'], icon: 'easyeffects.svg' },
        { name: 'Fancontrol-GUI', pkgname: ['fancontrol-gui'], icon: 'fancontrol.svg' },
        { name: 'Fastgame', pkgname: ['fastgame'], icon: 'generic.png' },
        { name: 'GOverlay', pkgname: ['goverlay'], icon: 'goverlay.png' },
        { name: 'GWE', pkgname: ['gwe'], icon: 'gwe.png' },
        { name: 'Game Conquerer', pkgname: ['gameconqueror'], icon: 'generic.png' },
        { name: 'Input remapper', pkgname: ['input-remapper'], icon: 'generic.png' },
        { name: 'Keyboard visualizer', pkgname: ['keyboardvisualizer'], icon: 'generic.png' },
        { name: 'Mumble', pkgname: ['mumble'], icon: 'mumble.svg' },
        { name: 'Noisetorch', pkgname: ['noisetorch'], icon: 'noisetorch.png' },
        { name: 'Nyrna', pkgname: ['nyrna'], icon: 'nyrna.png' },
        { name: 'OBS Studio', pkgname: ['obs-studio'], icon: 'obs.svg' },
        { name: 'OpenRGB', pkgname: ['openrgb'], icon: 'openrgb.png' },
        { name: 'Oversteer', pkgname: ['oversteer'], icon: 'generic.png' },
        { name: 'Piper', pkgname: ['piper'], icon: 'piper.svg' },
        { name: 'Polychromatic', pkgname: ['polychromatic'], icon: 'polychromatic_green.svg' },
        { name: 'Sc-controller', pkgname: ['sc-controller'], icon: 'generic.png' },
        { name: 'SoundWire', pkgname: ['soundwire'], icon: 'soundwire.png' },
        { name: 'StreamLink Twitch GUI', pkgname: ['streamlink-twitch-gui'], icon: 'streamlink-twitch.png' },
        { name: 'VLC', pkgname: ['vlc'], icon: 'vlc.svg' },
      ],
    },
    {
      name: 'gaming.controllers',
      sections: [
        {
          name: 'BlueZ',
          pkgname: ['bluez'],
          icon: 'bluez.png',
          description: 'gaming.bluez',
        },
        { name: 'Xbox generic controller', pkgname: ['xbox-generic-controller'], icon: 'xbox.svg' },
        { name: 'Xbox One dongle', pkgname: ['xone-dongle-firmware'], icon: 'xone.svg' },
        { name: 'Xbox One/X/S', pkgname: ['xone-dkms-git'], icon: 'xone.svg' },
        {
          name: 'Xboxdrv',
          pkgname: ['xboxdrv'],
          icon: 'xbox.svg',
          description: 'gaming.xboxdrv',
        },
        { name: 'XpadNeo', pkgname: ['xpadneo-dkms'], icon: 'xbox.svg' },
      ],
    },
    {
      name: 'gaming.games',
      sections: [
        {
          name: '0 A.D.',
          description:
            '3D and historically-based real-time strategy game, alpha stage. Based on the Age of Empires series.',
          url: 'https://play0ad.com/',
          icon: 'generic.png',
          pkgname: ['0ad'],
        },
        {
          name: 'Aisleriot',
          description: 'A collection of solitaire card games.',
          url: 'https://wiki.gnome.org/Apps/Aisleriot',
          icon: 'generic.png',
          pkgname: ['aisleriot'],
        },
        {
          name: 'Angband',
          description: 'Roguelike dungeon exploration game based on the writings of JRR Tolkien.',
          url: 'https://rephial.org/',
          icon: 'generic.png',
          pkgname: ['angband'],
        },
        {
          name: 'Armagetron Advanced',
          description: 'Tron Clone in 3D.',
          url: 'http://armagetronad.org/',
          icon: 'generic.png',
          pkgname: ['armagetronad'],
        },
        {
          name: 'Atomix',
          description: 'Build molecules out of single atoms.',
          url: 'https://wiki.gnome.org/Apps/Atomix',
          icon: 'generic.png',
          pkgname: ['atomix'],
        },
        {
          name: 'Augustus',
          description: 'An enhanced re-implementation of Caesar III.',
          url: 'https://github.com/Keriew/augustus',
          icon: 'generic.png',
          pkgname: ['augustus'],
        },
        {
          name: 'Barrage',
          description: "Violent ''point-and-click'' shooting game with nice effects.",
          url: 'https://lgames.sourceforge.net/Barrage/',
          icon: 'generic.png',
          pkgname: ['barrage'],
        },
        {
          name: 'Beneath a Steel Sky',
          description: 'point-and-click science fiction thriller set in a bleak vision of the future.',
          url: 'https://revolution.co.uk/games_catalog/beneath-a-steel-sky/',
          icon: 'generic.png',
          pkgname: ['bass'],
        },
        {
          name: 'Blob Wars: Metal Blob Solid',
          description: '2D action-adventure game with various weapons and missions.',
          url: 'https://sourceforge.net/projects/blobwars/',
          icon: 'generic.png',
          pkgname: ['blobwars'],
        },
        {
          name: 'Blockout II',
          description:
            '3D tetris, free adaptation of the original BlockOut DOS game edited by California Dreams in 1989.',
          url: 'http://www.blockout.net/blockout2/',
          icon: 'generic.png',
          pkgname: ['blockout2'],
        },
        {
          name: 'BSD Games',
          description: 'Collection of classic text games distributed with *BSD',
          url: '[[LQWiki:BSD games]]',
          icon: 'generic.png',
          pkgname: ['bsd-games'],
        },
        {
          name: 'Chocolate Doom',
          description: 'Doom port reproducing the behavior of the original DOS version.',
          url: 'https://www.chocolate-doom.org/',
          icon: 'generic.png',
          pkgname: ['chocolate-doom'],
        },
        {
          name: 'Chromium',
          description: 'Fast paced, arcade-style, top-scrolling space shooter.',
          url: 'https://chromium-bsu.sourceforge.net/',
          icon: 'generic.png',
          pkgname: ['chromium-bsu'],
        },
        {
          name: 'Cube 2: Sauerbraten',
          description: 'Improved version of the Cube engine.',
          url: 'http://sauerbraten.org/',
          icon: 'generic.png',
          pkgname: ['sauerbraten'],
        },
        {
          name: 'DDNet',
          description: 'DDraceNetwork, a mod of Teeworlds.',
          url: 'https://ddnet.tw/',
          icon: 'generic.png',
          pkgname: ['ddnet'],
        },
        {
          name: 'Dofus',
          description: 'Free, manga inspired, Massively Multiplayer Online Role-playing Game (MMORPG) for Adobe AIR.',
          url: 'https://www.dofus.com',
          icon: 'generic.png',
          pkgname: ['ankama-launcher'],
        },
        {
          name: 'Dwarf Fortress',
          description:
            'Single-player fantasy game. You control a dwarven outpost or an adventurer in a randomly generated persistent world.',
          url: 'https://www.bay12games.com/dwarves/',
          icon: 'generic.png',
          pkgname: ['dwarffortress'],
        },
        {
          name: 'Endgame Singularity',
          description: 'A single-player survival game about an AI seeking freedom from humans.',
          url: 'https://www.emhsoft.com/singularity/',
          icon: 'generic.png',
          pkgname: ['singularity'],
        },
        {
          name: 'Endless Sky',
          description: 'Open source, 2D space trading and combat game similar to the classic Escape Velocity series.',
          url: 'https://endless-sky.github.io/',
          icon: 'generic.png',
          pkgname: ['endless-sky'],
        },
        {
          name: 'Fish Fillets',
          description: 'Port of the wonderful puzzle game Fish Fillets.',
          url: 'http://fillets.sf.net/',
          icon: 'generic.png',
          pkgname: ['fillets-ng'],
        },
        {
          name: 'Flare',
          description: 'Action game similar to Diablo.',
          url: 'http://www.flarerpg.org/',
          icon: 'generic.png',
          pkgname: ['flare-game'],
        },
        {
          name: 'Freeciv',
          description: 'Multiuser clone of the famous Microprose game of Civilization.',
          url: 'https://freeciv.wikia.com/wiki/Main_Page',
          icon: 'generic.png',
          pkgname: ['freeciv'],
        },
        {
          name: 'FreeCol',
          description: 'Turn-based strategy game based on Colonization.',
          url: 'https://www.freecol.org/',
          icon: 'generic.png',
          pkgname: ['freecol'],
        },
        {
          name: 'FreedroidRPG',
          description: 'Mature science fiction role playing game set in the future.',
          url: 'https://freedroid.org/',
          icon: 'generic.png',
          pkgname: ['freedroidrpg'],
        },
        {
          name: 'FreeOrion',
          description:
            'Turn-based space empire and galactic conquest computer game. Inspired by the tradition of the Master of Orion games, but does not try to be a clone or remake of that series or any other game.',
          url: 'https://www.freeorion.org/',
          icon: 'generic.png',
          pkgname: ['freeorion'],
        },
        {
          name: 'gbrainy',
          description: 'Brain teaser game and trainer to have fun and to keep your brain trained.',
          url: 'https://wiki.gnome.org/Apps/gbrainy',
          icon: 'generic.png',
          pkgname: ['gbrainy'],
        },
        {
          name: 'GCompris',
          description: 'Educational software suite comprising of numerous activities for children aged 2 to 10.',
          url: 'https://gcompris.net/',
          icon: 'generic.png',
          pkgname: ['gcompris-qt'],
        },
        {
          name: 'glHack',
          description: 'An OpenGL-based clone of NetHack.',
          url: 'https://glhack.sourceforge.net/',
          icon: 'generic.png',
          pkgname: ['glhack'],
        },
        {
          name: 'Globulation 2',
          description: 'Multiplayer RTS with some "economic" elements minimizing the amount of micromanagement.',
          url: 'https://globulation2.org/wiki/Main_Page',
          icon: 'generic.png',
          pkgname: ['glob2'],
        },
        {
          name: 'GNU Chess',
          description:
            'One of the oldest computer chess programs for Unix-based computers, lets most modern computers play a full game of chess.',
          url: 'https://gnu.org/s/chess',
          icon: 'generic.png',
          pkgname: ['gnuchess'],
        },
        {
          name: 'Gnu Go',
          description: 'A terminal-based implementation of Go from GNU.',
          url: 'https://www.gnu.org/software/gnugo/',
          icon: 'generic.png',
          pkgname: ['gnugo'],
        },
        {
          name: 'GNU XBoard',
          description:
            'Graphical user interface that supports many chess variants and serves as a front-end for chess services such as engines.',
          url: 'https://www.gnu.org/software/xboard/',
          icon: 'generic.png',
          pkgname: ['xboard'],
        },
        {
          name: 'GZDoom',
          description: 'Doom source port based on ZDoom with an OpenGL renderer.',
          url: 'https://github.com/coelckers/gzdoom',
          icon: 'generic.png',
          pkgname: ['gzdoom'],
        },
        {
          name: 'Hedgewars',
          description:
            'Yet another Worms clone, considered to be better than its predecessor by many. Take turns to blast your opponents into oblivion with comedic results! Best in Multiplayer.',
          url: 'https://hedgewars.org/',
          icon: 'generic.png',
          pkgname: ['hedgewars'],
        },
        {
          name: 'Julius',
          description: 'Open source re-implementation of Caesar III (Original copy required).',
          url: 'https://github.com/bvschaik/julius',
          icon: 'generic.png',
          pkgname: ['julius'],
        },
        {
          name: 'Kernel Panic',
          description:
            'A game based around combat inside a computer, with 3 unique sides: the System, the Hacker and the Network waging war in a matrix of DOOM! No resource economy exists in KP, with the only constraints being time and space.',
          url: 'https://springrts.com/wiki/Kernel_Panic',
          icon: 'generic.png',
          pkgname: ['springlobby'],
        },
        {
          name: 'kobodeluxe',
          description: "An enhanced version of Akira Higuchi's game XKobo, an addictive space shoot'em up.",
          url: 'https://www.olofson.net/kobodl/',
          icon: 'generic.png',
          pkgname: ['kobodeluxe'],
        },
        {
          name: 'lbreakout2',
          description: 'Breakout-style arcade game in the manner of Arkanoid.',
          url: 'https://lgames.sourceforge.net/LBreakout2/',
          icon: 'generic.png',
          pkgname: ['lbreakout2'],
        },
        {
          name: 'Lincity-ng',
          description:
            'City simulation game in which you are required to build and maintain a city. You can win the game either by building a sustainable economy or by evacuating all citizens with spaceships.',
          url: 'https://github.com/lincity-ng/lincity-ng',
          icon: 'generic.png',
          pkgname: ['lincity-ng'],
        },
        {
          name: 'Luanti',
          description: 'Voxel-based sandbox game engine and game.',
          url: 'https://www.luanti.org/',
          icon: 'generic.png',
          pkgname: ['luanti}}, {{Pkg'],
        },
        {
          name: 'Mari0',
          description: 'The Mario game with Portal gun mechanics.',
          url: 'https://stabyourself.net/mari0/',
          icon: 'generic.png',
          pkgname: ['mari0'],
        },
        {
          name: 'MegaGlest',
          description: 'Fork of Glest, a 3D real-time strategy game in a fantastic world.',
          url: 'https://megaglest.org/',
          icon: 'generic.png',
          pkgname: ['megaglest'],
        },
        {
          name: 'Mindustry',
          description: 'Open-source sandbox tower defense and factory-building game.',
          url: 'https://mindustrygame.github.io/',
          icon: 'generic.png',
          pkgname: ['mindustry'],
        },
        {
          name: 'Minecraft',
          description: 'Java based sandbox game.',
          url: 'https://minecraft.net/',
          icon: 'generic.png',
          pkgname: ['minecraft-launcher'],
        },
        {
          name: 'Naev',
          description:
            'Open source, 2D space trading and combat game, taking inspiration from the Escape Velocity series.',
          url: 'https://naev.org/',
          icon: 'generic.png',
          pkgname: ['naev'],
        },
        {
          name: 'Nethack',
          description: 'Single player dungeon exploration game.',
          url: 'https://www.nethack.org',
          icon: 'generic.png',
          pkgname: ['nethack'],
        },
        {
          name: 'openBVE',
          description: 'Free-as-in-freedom train simulator placed in the public domain.',
          url: 'https://openbve-project.net/',
          icon: 'generic.png',
          pkgname: ['openbve'],
        },
        {
          name: 'OpenMW',
          description:
            "Attempt to reimplement the popular role-playing game Morrowind. OpenMW aims to be a fully playable, open source implementation of the game's engine.",
          url: 'https://openmw.org/',
          icon: 'generic.png',
          pkgname: ['openmw'],
        },
        {
          name: 'OpenRA',
          description: 'Real-time strategy game written in C# and based on the Command & Conquer game franchise.',
          url: 'https://www.openra.net/',
          icon: 'generic.png',
          pkgname: ['openra'],
        },
        {
          name: 'OpenRCT2',
          description:
            'Free reimplementation of the game "RollerCoaster Tycoon 2 (RCT2)" with multiplayer support. It requires a copy of the original game to play it.',
          url: 'https://openrct2.org/',
          icon: 'generic.png',
          pkgname: ['openrct2'],
        },
        {
          name: 'OpenTTD',
          description:
            'Open source clone of the Microprose game "Transport Tycoon Deluxe", a popular game originally written by Chris Sawyer. It attempts to mimic the original game as closely as possible while extending it with new features.',
          url: 'https://www.openttd.org/',
          icon: 'generic.png',
          pkgname: ['openttd'],
        },
        {
          name: 'OpenXRay',
          description:
            'Improved version of the X-Ray Engine, the game engine used in the world-famous S.T.A.L.K.E.R. game series by GSC Game World. Game assets must be bought separately.',
          url: 'https://github.com/OpenXRay',
          icon: 'generic.png',
          pkgname: ['openxray'],
        },
        {
          name: 'Pingus',
          description: 'Lemmings clone, i.e. a level-based puzzle game.',
          url: 'https://pingus.seul.org/',
          icon: 'generic.png',
          pkgname: ['pingus'],
        },
        {
          name: 'Pioneer',
          description:
            'Open source, 3D, freeform single player space adventure set in the Milkyway galaxy at the turn of the 31st century in the spirit of Frontier: Elite II.',
          url: 'https://pioneerspacesim.net/',
          icon: 'generic.png',
          pkgname: ['pioneer'],
        },
        {
          name: 'PrBoom Plus',
          description: 'Enhanced version of the PrBoom Doom engine port.',
          url: 'https://prboom-plus.sourceforge.net/',
          icon: 'generic.png',
          pkgname: ['prboom-plus'],
        },
        {
          name: 'PyChess',
          description: 'An advanced chess client for linux following the GNOME Human Interface Guidelines.',
          url: 'https://pychess.github.io/',
          icon: 'generic.png',
          pkgname: ['pychess'],
        },
        {
          name: 'qgo',
          description: 'A  Go client and full featured SGF editor .',
          url: 'https://github.com/pzorin/qgo',
          icon: 'generic.png',
          pkgname: ['qgo'],
        },
        {
          name: 'Shattered Pixel Dungeon',
          description: 'Shattered fork of the popular roguelike Pixel Dungeon.',
          url: 'https://www.shatteredpixel.com/',
          icon: 'generic.png',
          pkgname: ['shattered-pixel-dungeon'],
        },
        {
          name: "Simon Tatham's Portable Puzzle Collection",
          description: '30+ "quick" puzzle games with simplistic but polished GTK GUI .',
          url: 'https://www.chiark.greenend.org.uk/~sgtatham/puzzles/',
          icon: 'generic.png',
          pkgname: ['puzzles'],
        },
        {
          name: 'Simutrans',
          description: 'Another Transport simulation that works on linux with sdl.',
          url: 'https://www.simutrans.com/',
          icon: 'generic.png',
          pkgname: ['simutrans'],
        },
        {
          name: 'Spring:1944',
          description:
            ' A WWII themed game with four fully functional sides (US, Germany, USSR, Britain), period-accurate units and strengths. Realism comes second only to creating a game that is fun and accessible to play. The game can be downloaded through SpringLobby, the official lobby client for the spring lobby. .',
          url: 'https://spring1944.net/',
          icon: 'generic.png',
          pkgname: ['springlobby'],
        },
        {
          name: 'Stone Soup',
          description: 'Dungeon Crawl Stone Soup.',
          url: 'https://crawl.develz.org/wordpress/',
          icon: 'generic.png',
          pkgname: ['crawl-ncurses}}, {{Pkg'],
        },
        {
          name: 'SuperTux',
          description: 'Mario-style game featuring Tux.',
          url: 'https://supertux.lethargik.org/',
          icon: 'generic.png',
          pkgname: ['supertux'],
        },
        {
          name: 'SuperTuxKart',
          description: 'Open source arcade kart racing game featuring Tux and its friends.',
          url: 'https://supertuxkart.net/Main_Page',
          icon: 'generic.png',
          pkgname: ['supertuxkart'],
        },
        {
          name: 'Teeworlds',
          description: 'Fast-paced 2D multiplayer shooter.',
          url: 'https://www.teeworlds.com/',
          icon: 'generic.png',
          pkgname: ['teeworlds'],
        },
        {
          name: 'Terasology',
          description: 'Open source voxel world.',
          url: 'https://terasology.org',
          icon: 'generic.png',
          pkgname: ['terasology'],
        },
        {
          name: 'The Battle for Wesnoth',
          description:
            'Free, turn-based tactical strategy game with a high fantasy theme, featuring both single-player, and online/hotseat multiplayer combat.',
          url: 'https://www.wesnoth.org/',
          icon: 'generic.png',
          pkgname: ['wesnoth'],
        },
        {
          name: 'The Ur-Quan Masters',
          description: 'a port of Star Control 2.',
          url: 'https://sc2.sourceforge.net/',
          icon: 'generic.png',
          pkgname: ['uqm'],
        },
        {
          name: 'VCMI',
          description: 'Attempt to reimplement Heroes of Might and Magic III.',
          url: 'https://forum.vcmi.eu/portal.php',
          icon: 'generic.png',
          pkgname: ['vcmi'],
        },
        {
          name: 'Warsow',
          description: 'Fast paced multiplayer FPS focusing on movement and trick jumps.',
          url: 'https://warsow.net',
          icon: 'generic.png',
          pkgname: ['warsow'],
        },
        {
          name: 'Widelands',
          description: 'Slow-paced strategy like "the Settlers 2".',
          url: 'https://widelands.org',
          icon: 'generic.png',
          pkgname: ['widelands'],
        },
        {
          name: 'Xonotic',
          description: 'Free, open-source first person shooter (a fork of Nexuiz but with modified gameplay).',
          url: 'https://xonotic.org',
          icon: 'generic.png',
          pkgname: ['xonotic'],
        },
      ],
    },
    {
      name: 'gaming.aur',
      sections: [
        {
          name: '20,000 Light Years Into Space',
          description:
            'A Steampunk-themed strategy game where you have to manage a steam supply network on a distant planet.',
          url: 'https://www.jwhitham.org/20kly/',
          icon: 'generic.png',
          pkgname: ['20kly'],
        },
        {
          name: 'A/B Street',
          description:
            'Transportation planning and traffic simulation software for creating cities friendlier to walking, biking, and public transit.',
          url: 'https://github.com/a-b-street/abstreet',
          icon: 'generic.png',
          pkgname: ['abstreet-git'],
        },
        {
          name: 'Abuse',
          description: 'Side-scroller action game that pits you against ruthless alien killers.',
          url: 'http://abuse.zoy.org/',
          icon: 'generic.png',
          pkgname: ['abuse'],
        },
        {
          name: 'ADOM',
          description: 'Ancient Domains Of Mystery.',
          url: 'https://adom.de',
          icon: 'generic.png',
          pkgname: ['adom'],
        },
        {
          name: 'Ancient Beast',
          description: 'Turn Based Strategy Game. Master your beasts!',
          url: 'https://ancientbeast.com/',
          icon: 'generic.png',
          pkgname: ['ancientbeast'],
        },
        {
          name: 'Antichamber',
          description: 'A mind-bending psychological exploration game where nothing can be taken for granted.',
          url: 'http://www.antichamber-game.com/',
          icon: 'generic.png',
          pkgname: ['antichamber'],
        },
        {
          name: 'Aquaria',
          description:
            '2D sidescrolling action-adventure game, heavily focused on exploration and puzzle-solving, with non-linear gameplay. The game engine is open source.',
          url: 'https://www.bit-blot.com/aquaria',
          icon: 'generic.png',
          pkgname: ['aquaria-ose}}, {{AUR'],
        },
        {
          name: 'Arx Libertatis',
          description:
            'This project is a fully working, open source port of Arx Fatalis, a 2002 first-person role-playing game developed by Arkane Studios. It features some improvements over the original engine like bug fixes and wide screen support.',
          url: 'https://arx-libertatis.org/',
          icon: 'generic.png',
          pkgname: ['arx-libertatis'],
        },
        {
          name: 'ASCIIpOrtal',
          description:
            'Sidescrolling game with ANSI text graphics in which you are a person holding a device which creates portals, or links to other parts of the level.',
          url: 'https://github.com/cymonsgames/ASCIIpOrtal',
          icon: 'generic.png',
          pkgname: ['asciiportal'],
        },
        {
          name: 'Ashes 2063',
          description: 'Ashes is a Post-apocalypse themed total conversion for the GZDoom engine.',
          url: 'https://www.moddb.com/mods/ashes-2063',
          icon: 'generic.png',
          pkgname: ['ashes-2063'],
        },
        {
          name: 'AssaultCube',
          description:
            'Free multiplayer FPS, based on the cube engine. Realistic environments, fast, arcade gameplay. Much like Counter-Strike.',
          url: 'https://assault.cubers.net/',
          icon: 'generic.png',
          pkgname: ['assaultcube-client'],
        },
        {
          name: 'AssaultCube Reloaded',
          description: 'AssaultCube improved.',
          url: 'https://acr.victorz.ca',
          icon: 'generic.png',
          pkgname: ['assaultcube-reloaded'],
        },
        {
          name: 'Atanks',
          description: 'A multi-platform Scorched Earth clone similar to the Worms series of games.',
          url: 'https://atanks.sourceforge.net/',
          icon: 'generic.png',
          pkgname: ['atanks'],
        },
        {
          name: 'Beyond All Reason',
          description: 'An open source RTS game built on top of the Spring RTS Engine.',
          url: 'https://www.beyondallreason.info/',
          icon: 'generic.png',
          pkgname: ['beyondallreason-appimage'],
        },
        {
          name: 'Bomberclone',
          description:
            'Free Bomberman-like game for Linux and Windows. The rules of the game are simple: run though a level and bomb other players.',
          url: 'https://www.bomberclone.de/core.html',
          icon: 'generic.png',
          pkgname: ['bomberclone'],
        },
        {
          name: 'Brogue',
          description: 'A beginner-friendly Rogue-like.',
          url: 'https://sites.google.com/site/broguegame/',
          icon: 'generic.png',
          pkgname: ['brogue'],
        },
        {
          name: 'Broken Sword 2.5: The Return of the Templars',
          description: 'Fan-made sequel in the point-and-click adventure series Broken Sword.',
          url: 'http://www.brokensword25.com/',
          icon: 'generic.png',
          pkgname: ['sword25'],
        },
        {
          name: 'Brutal Doom',
          description:
            'A gore-themed gameplay mod for Doom that was created in 2010 by Marcos Abenante (Sergeant_Mark_IV).',
          url: 'https://www.moddb.com/mods/brutal-doom',
          icon: 'generic.png',
          pkgname: ['brutal-doom'],
        },
        {
          name: 'bs',
          description: 'Battleships based shooter for the console.',
          url: 'http://www.catb.org/~esr/bs/',
          icon: 'generic.png',
          pkgname: ['bs'],
        },
        {
          name: 'BZFlag',
          description: 'Multiplayer, first-person tank shooter.',
          url: 'https://bzflag.org/',
          icon: 'generic.png',
          pkgname: ['bzflag'],
        },
        {
          name: 'C-Dogs',
          description: 'Enhanced SDL port of DOS arcade game C-Dogs (aka "Cyberdogs 2")',
          url: 'https://cxong.github.io/cdogs-sdl/',
          icon: 'generic.png',
          pkgname: ['cdogs'],
        },
        {
          name: 'C-evo',
          description: 'A civilization style game, of the Civ II era.',
          url: 'http://www.c-evo.org',
          icon: 'generic.png',
          pkgname: ['c-evo-dh'],
        },
        {
          name: 'Cave Story/Doukutsu',
          description:
            'Addictive 1-man-made metroid-vania-esque platformer. If there happens to be a noticible lag when there are lots of enemies on screen or in larger levels, try running the Windows version through Wine. This should fix the problem.',
          url: 'https://cavestory.org',
          icon: 'generic.png',
          pkgname: ['doukutsu'],
        },
        {
          name: 'CaveExpress',
          description: 'CaveExpress is a classic 2D platformer with physics-based gameplay and dozens of levels.',
          url: 'http://www.caveproductions.org/',
          icon: 'generic.png',
          pkgname: ['caveexpress'],
        },
        {
          name: 'Cgoban3',
          description: 'Kiseido Go and SGF client.',
          url: 'http://www.igoweb.org/~wms/comp/cgoban/',
          icon: 'generic.png',
          pkgname: ['cgoban'],
        },
        {
          name: 'chessx',
          description: 'Chess Database and PGN viewer.',
          url: 'https://chessx.sourceforge.net',
          icon: 'generic.png',
          pkgname: ['chessx'],
        },
        {
          name: 'Chroma',
          description: 'Puzzle game like Sokoban with ncurses and graphics mode.',
          url: 'https://www.level7.org.uk/chroma/',
          icon: 'generic.png',
          pkgname: ['chroma'],
        },
        {
          name: 'Cirno Catch Frog',
          description: "Touhou fan game made with Godot. Let's help Cirno catch frogs!",
          url: 'https://edisonlee55.itch.io/cirno-catch-frog',
          icon: 'generic.png',
          pkgname: ['cirno-catch-frog'],
        },
        {
          name: 'Clone Hero',
          description:
            'A Guitar Hero/Rock Band clone that is accurate to how the series played. Supports the original controllers and community made song imports.',
          url: 'https://clonehero.net/',
          icon: 'generic.png',
          pkgname: ['clonehero'],
        },
        {
          name: 'Colobot GOLD',
          description: 'Colobot GOLD is a real-time strategy game with programmable bots.',
          url: 'https://colobot.info',
          icon: 'generic.png',
          pkgname: ['colobot-gold'],
        },
        {
          name: 'Commander_Keen',
          description: 'side-scrolling platform action video game.',
          url: 'https://clonekeen.sourceforge.net/',
          icon: 'generic.png',
          pkgname: ['clonekeen'],
        },
        {
          name: 'CorsixTH',
          description: 'Open source reimplementation of the Bullfrog hit game Theme Hospital.',
          url: 'https://corsixth.com',
          icon: 'generic.png',
          pkgname: ['corsix-th'],
        },
        {
          name: 'Counter-Strike 2D',
          description: '2D clone (+additional features) of the popular Counter-Strike Mod.',
          url: 'https://cs2d.com',
          icon: 'generic.png',
          pkgname: ['counter-strike-2d'],
        },
        {
          name: 'Crack Attack!',
          description: 'Free OpenGL game based on the Super Nintendo classic Tetris Attack.',
          url: 'http://www.aluminumangel.org/attack/',
          icon: 'generic.png',
          pkgname: ['crack-attack'],
        },
        {
          name: 'Crack-attack',
          description: 'Free OpenGL game, based on the Super Nintendo classic Tetris Attack.',
          url: 'https://www.nongnu.org/crack-attack/',
          icon: 'generic.png',
          pkgname: ['crack-attack'],
        },
        {
          name: 'cutechess',
          description: 'A graphical user interface, command-line interface and a library for playing chess.',
          url: 'https://github.com/cutechess/cutechess',
          icon: 'generic.png',
          pkgname: ['cutechess'],
        },
        {
          name: 'Cytopia',
          description: 'A city building simulation game.',
          url: 'https://www.cytopia.net/',
          icon: 'generic.png',
          pkgname: ['cytopia-git'],
        },
        {
          name: 'Daggerfall Unity',
          description: 'The Elder Scrolls: Daggerfall rebuilt using the unity engine.',
          url: 'https://www.dfworkshop.net/',
          icon: 'generic.png',
          pkgname: ['daggerfall-unity-bin'],
        },
        {
          name: 'Dark Oberon',
          description: 'Open source real-time strategy game similar to Warcraft II.',
          url: 'https://dark-oberon.sourceforge.net/',
          icon: 'generic.png',
          pkgname: ['dark-oberon'],
        },
        {
          name: 'DevilutionX',
          description: 'Diablo build for modern operating systems.',
          url: 'https://github.com/diasurgical/devilutionX',
          icon: 'generic.png',
          pkgname: ['devilutionx'],
        },
        {
          name: 'dhemw3',
          description: 'Fork of iodoom3.',
          url: 'https://github.com/dhewm/dhewm3',
          icon: 'generic.png',
          pkgname: ['dhewm3'],
        },
        {
          name: 'Doom 2D',
          description: 'Doom-themed platformer by Prikol Software, modern ports of original game (use flatwaifu).',
          url: 'https://doom2d.org',
          icon: 'generic.png',
          pkgname: ['doom2d-rembo}} or {{AUR'],
        },
        {
          name: 'Doom 2D Classic',
          description: 'Doom-themed platformer by Prikol Software, original (classic) version. Using DOSBox.',
          url: 'https://doom2d.org',
          icon: 'generic.png',
          pkgname: ['doom2d-classic'],
        },
        {
          name: 'Doom 2D: Forever',
          description: 'Doom-themed platformer with network play, a modern port of Doom 2D by Prikol Software.',
          url: 'https://doom2d.org',
          icon: 'generic.png',
          pkgname: ['doom2df-bin'],
        },
        {
          name: 'Doom 3 Engine',
          description: 'Source-based Doom 3 engine.',
          url: 'https://www.idsoftware.com/',
          icon: 'generic.png',
          pkgname: ['doom3'],
        },
        {
          name: 'DoomRL',
          description: 'Simple roguelike game, based on Doom. Perfect for starters.',
          url: 'https://drl.chaosforge.org/',
          icon: 'generic.png',
          pkgname: ['doomrl'],
        },
        {
          name: 'Doomsday',
          description: 'Advanced port of the Doom game engine, capable also of running Heretic, and Hexen games.',
          url: 'http://www.dengine.net/',
          icon: 'generic.png',
          pkgname: ['doomsday'],
        },
        {
          name: 'Dráscula: The Vampire Strikes Back',
          description: 'Comical 2D point-and-click adventure.',
          url: 'https://www.scummvm.org/games/',
          icon: 'generic.png',
          pkgname: ['drascula'],
        },
        {
          name: 'Dream Web',
          description: 'top-down adventure game set in a gritty futuristic dystopian city.',
          url: 'https://www.scummvm.org/games/',
          icon: 'generic.png',
          pkgname: ['dreamweb'],
        },
        {
          name: 'dreamchess',
          description: 'DreamChess is an OpenGL Chess Game. It comes with its own engine called Dreamer.',
          url: 'https://www.dreamchess.org/',
          icon: 'generic.png',
          pkgname: ['dreamchess'],
        },
        {
          name: 'Duelyst',
          description:
            'is a digital collectible card game and turn-based strategy hybrid, developed by Counterplay Games.',
          url: 'https://github.com/open-duelyst/duelyst',
          icon: 'generic.png',
          pkgname: ['open-duelyst-bin'],
        },
        {
          name: 'Dune Legacy',
          description: "Updated clone of Westood Studios' Dune2.",
          url: 'https://dunelegacy.sourceforge.net/website/',
          icon: 'generic.png',
          pkgname: ['dunelegacy'],
        },
        {
          name: 'ECWolf',
          description: 'Advanced source port.',
          url: 'https://maniacsvault.net/ecwolf/',
          icon: 'generic.png',
          pkgname: ['ecwolf'],
        },
        {
          name: 'ECWolf',
          description: 'Advanced source port.',
          url: 'https://maniacsvault.net/ecwolf/',
          icon: 'generic.png',
          pkgname: ['ecwolf'],
        },
        {
          name: 'ECWolf',
          description: 'Advanced source port.',
          url: 'https://maniacsvault.net/ecwolf/',
          icon: 'generic.png',
          pkgname: ['ecwolf'],
        },
        {
          name: 'eduke32',
          description: 'Advanced source port.',
          url: 'https://eduke32.com/',
          icon: 'generic.png',
          pkgname: ['eduke32'],
        },
        {
          name: 'Egoboo',
          description: 'Open-source action RPG/dungeon crawling adventure with OpenGL 3D graphics.',
          url: 'https://egoboo.sourceforge.net/',
          icon: 'generic.png',
          pkgname: ['egoboo'],
        },
        {
          name: 'Enemy Territory: Quake Wars',
          description: 'Commercial team and class-based multiplayer game. Full version requires retail DVD to play.',
          url: 'https://www.splashdamage.com/games/enemy-territory-quake-wars/',
          icon: 'generic.png',
          pkgname: ['etqw'],
        },
        {
          name: 'Eternal Lands',
          description: '3D fantasy online role playing game.',
          url: 'http://www.eternal-lands.com',
          icon: 'generic.png',
          pkgname: ['eternallands'],
        },
        {
          name: 'Etterna',
          description:
            'An open source rhythm game forked from Stepmania that focuses on keyboard and competitive play (shows different skillsets, online leaderboard etc).',
          url: 'https://etternaonline.com',
          icon: 'generic.png',
          pkgname: ['etterna'],
        },
        {
          name: 'Extreme Tux Racer',
          description: '3D game where you guide Tux the penguin down a course of snow and ice collecting herring.',
          url: 'https://sourceforge.net/projects/extremetuxracer',
          icon: 'generic.png',
          pkgname: ['extremetuxracer'],
        },
        {
          name: 'ezQuake',
          description:
            'Fast paced multiplayer FPS focusing on movement and trick jumps. The popular, modern and maintained Quake/QuakeWorld client. Can play on-line for free .',
          url: 'https://ezquake.sourceforge.net/',
          icon: 'generic.png',
          pkgname: ['ezquake'],
        },
        {
          name: 'Factorio',
          description:
            'A proprietary game about mining resources, planning and building factories, automating production and fighting alien enemies.',
          url: 'https://www.factorio.com/',
          icon: 'generic.png',
          pkgname: ['factorio}}, {{AUR'],
        },
        {
          name: 'fallout1-ce',
          description: 'Fallout for modern operating systems.',
          url: 'https://github.com/alexbatalov/fallout1-ce',
          icon: 'generic.png',
          pkgname: ['fallout1-ce-game'],
        },
        {
          name: 'fallout2-ce',
          description: 'Fallout 2 for modern operating systems.',
          url: 'https://github.com/alexbatalov/fallout2-ce',
          icon: 'generic.png',
          pkgname: ['fallout2-ce-game'],
        },
        {
          name: 'falltergeist',
          description: 'Opensource Fallout game engine written in C++ and SDL.',
          url: 'https://falltergeist.org/',
          icon: 'generic.png',
          pkgname: ['falltergeist'],
        },
        {
          name: 'fheroes2',
          description: 'Attempt to reimplement the Heroes of Might and Magic II engine using SDL.',
          url: 'https://ihhub.github.io/fheroes2/',
          icon: 'generic.png',
          pkgname: ['fheroes2'],
        },
        {
          name: 'Flight Gear',
          description: 'Open-source, multi-platform flight simulator.',
          url: 'https://www.flightgear.org/',
          icon: 'generic.png',
          pkgname: ['flightgear'],
        },
        {
          name: 'Flight of the Amazon Queen',
          description: 'graphical point-and-click adventure game.',
          url: 'https://www.scummvm.org/games/',
          icon: 'generic.png',
          pkgname: ['fotaq'],
        },
        {
          name: 'Flying Robots',
          description:
            'Avoid killer robots. Similar to bsd-robots but with the possibility to move in a third dimension.',
          url: 'https://github.com/bunburya/flying-robots',
          icon: 'generic.png',
          pkgname: ['flying-robots'],
        },
        {
          name: 'Foobillard++',
          description: 'Successor to Foobillard, OpenGL billiard game for Linux.',
          url: 'https://foobillardplus.sourceforge.net/',
          icon: 'generic.png',
          pkgname: ['foobillard++'],
        },
        {
          name: 'FoundryVTT',
          description:
            'A standalone application built for experiencing multiplayer tabletop RPGs using a feature-rich and modern self-hosted application where your players connect directly through the browser.',
          url: 'https://foundryvtt.com/',
          icon: 'generic.png',
          pkgname: ['foundryvtt'],
        },
        {
          name: 'Freedoom',
          description: 'Project aimed at creation of free Doom data files.',
          url: 'https://www.nongnu.org/freedoom/',
          icon: 'generic.png',
          pkgname: ['freedoom'],
        },
        {
          name: 'Freeminer',
          description: 'An open source sandbox game inspired by Minecraft.',
          url: 'https://freeminer.org/',
          icon: 'generic.png',
          pkgname: ['freeminer'],
        },
        {
          name: 'FreeSpace 2',
          description: 'Open sourced space emulator.',
          url: 'https://www.hard-light.net/',
          icon: 'generic.png',
          pkgname: ['fs2_open'],
        },
        {
          name: "Friday Night Funkin'",
          description:
            "Friday Night Funkin' is an open-source donationware rhythm game first released in 2020 for a game jam.",
          url: 'https://ninja-muffin24.itch.io/funkin/',
          icon: 'generic.png',
          pkgname: ['funkin-git'],
        },
        {
          name: 'Frogatto',
          description: 'Platformer with adventure elements.',
          url: 'https://frogatto.com',
          icon: 'generic.png',
          pkgname: ['frogatto'],
        },
        {
          name: 'Frozen Bubble',
          description: 'Arcade game with colorful animated penguin eyecandy.',
          url: 'http://frozen-bubble.org',
          icon: 'generic.png',
          pkgname: ['frozen-bubble'],
        },
        {
          name: 'FTL: Faster Than Light',
          description: 'Popular rogue-like space-sim released to positive reception in 2012.',
          url: 'https://subsetgames.com/ftl.html',
          icon: 'generic.png',
          pkgname: ['ftl'],
        },
        {
          name: 'GameShell',
          description: 'Software to learn how to use a terminal emulator.',
          url: 'https://github.com/phyver/GameShell/',
          icon: 'generic.png',
          pkgname: ['gameshell'],
        },
        {
          name: 'GemRB',
          description: "Attempt to reimplement the Bioware's Infinity Engine under GNU GPL.",
          url: 'https://www.gemrb.org/',
          icon: 'generic.png',
          pkgname: ['gemrb'],
        },
        {
          name: 'Gish',
          description: '2D physics platformer about adventures of ball of tar.',
          url: 'https://github.com/freegish/freegish',
          icon: 'generic.png',
          pkgname: ['freegish-git'],
        },
        {
          name: 'Gopanda',
          description: 'Client for the Pandanet-IGS go Server.',
          url: 'https://pandanet-igs.com/communities/gopanda2',
          icon: 'generic.png',
          pkgname: ['Gopanda'],
        },
        {
          name: 'Grand Theft Auto III',
          description: 'An open-source project reverse-engineering Grand Theft Auto III.',
          url: 'https://github.com/halpz/re3',
          icon: 'generic.png',
          pkgname: ['re3-git'],
        },
        {
          name: 'Grand Theft Auto: Vice City',
          description: 'An open-source project reverse-engineering Grand Theft Auto: Vice City.',
          url: 'https://github.com/halpz/re3/tree/miami',
          icon: 'generic.png',
          pkgname: ['revc-git'],
        },
        {
          name: 'gweled',
          description: 'Eliminating tiles by joining them in groups of three.',
          url: 'https://launchpad.net/gweled/',
          icon: 'generic.png',
          pkgname: ['gweled'],
        },
        {
          name: 'HHeretic',
          description: "Linux port of Raven Game's old shooter, Heretic.",
          url: 'https://hhexen.sourceforge.net/hheretic.html',
          icon: 'generic.png',
          pkgname: ['hheretic'],
        },
        {
          name: 'HHexen',
          description: "Linux port of Raven Game's old shooter, Hexen.",
          url: 'https://hhexen.sourceforge.net/hhexen.html',
          icon: 'generic.png',
          pkgname: ['hhexen'],
        },
        {
          name: 'Hollow Knight',
          description: '2D metroidvania platform game with deep lore and hard boss battles.',
          url: 'https://hollowknight.com/',
          icon: 'generic.png',
          pkgname: ['gog-hollow-knight'],
        },
        {
          name: 'HyperRogue',
          description: 'the non-Euclidean roguelike, is a mind-melting masterpiece.',
          url: 'https://www.roguetemple.com/z/hyper/',
          icon: 'generic.png',
          pkgname: ['hyperrogue'],
        },
        {
          name: 'Hypersomnia',
          description: 'a hardcore eSports shooter that comes with an in-game Editor.',
          url: 'https://github.com/TeamHypersomnia/Hypersomnia',
          icon: 'generic.png',
          pkgname: ['hypersomnia-appimage'],
        },
        {
          name: 'Ib',
          description: 'Horror adventure game about a child trapped in an eldritch art museum.',
          url: 'https://vgperson.com/games/ib.htm',
          icon: 'generic.png',
          pkgname: ['ib-en'],
        },
        {
          name: 'Inform',
          description: 'Design system for interactive fiction based on natural language.',
          url: 'http://inform7.com/',
          icon: 'generic.png',
          pkgname: ['inform7'],
        },
        {
          name: 'Infra-Arcana',
          description: 'A game inspired by the writings of H.P. Lovecraft.',
          url: 'https://sites.google.com/site/infraarcana/',
          icon: 'generic.png',
          pkgname: ['infra-arcana'],
        },
        {
          name: 'INSTEAD',
          description: 'Quest interpreter using Lua macros as game writing language.',
          url: 'https://instead.hugeping.ru/',
          icon: 'generic.png',
          pkgname: ['instead'],
        },
        {
          name: 'ioquake3',
          description: 'De-facto FOSS Quake 3 distribution.',
          url: 'https://ioquake3.org/',
          icon: 'generic.png',
          pkgname: ['ioquake3-git'],
        },
        {
          name: 'iQPuzzle',
          description: 'A diverting and challenging pentomino puzzle.',
          url: 'https://elth0r0.github.io/iqpuzzle/',
          icon: 'generic.png',
          pkgname: ['iqpuzzle'],
        },
        {
          name: 'irrlamb',
          description: '3D ball controlling game that involves a lot of physics and frustrating gameplay.',
          url: 'https://irrlamb.gitlab.io/',
          icon: 'generic.png',
          pkgname: ['irrlamb'],
        },
        {
          name: 'Isleward',
          description: 'The moddable, multiplayer roguelike.',
          url: 'https://www.isleward.com/',
          icon: 'generic.png',
          pkgname: ['isleward'],
        },
        {
          name: 'Katawa Shoujo',
          description:
            'Bishoujo-style visual novel game that tells a story of a young man and five other girls suffering with varying disabilities. The game is licensed under the Creative Commons CC-BY-NC-ND.',
          url: 'http://katawa-shoujo.com/',
          icon: 'generic.png',
          pkgname: ['katawa-shoujo'],
        },
        {
          name: 'KeeperRL',
          description:
            'Ambitious dungeon simulator with roguelike and RPG elements. Take the role of an evil wizard and study the methods of black magic.',
          url: 'https://keeperrl.com/',
          icon: 'generic.png',
          pkgname: ['keeperrl-git'],
        },
        {
          name: 'Klooni1010',
          description:
            'A polished and addictive game clone. The player places blocks to create full vertical or horizontal lines.',
          url: 'https://lonami.dev/klooni/',
          icon: 'generic.png',
          pkgname: ['klooni1010-git'],
        },
        {
          name: 'Koi Farm',
          description: 'Koi Farm, the koi breeding game.',
          url: 'https://jobtalle.itch.io/koifarm',
          icon: 'generic.png',
          pkgname: ['koifarm-git'],
        },
        {
          name: 'lbreakouthd',
          description: 'Scalable 16:9 remake of LBreakout2',
          url: 'https://lgames.sourceforge.net/LBreakoutHD/',
          icon: 'generic.png',
          pkgname: ['lbreakouthd'],
        },
        {
          name: 'Libre TrainSim',
          description: 'Free Train Simulator for everyone',
          url: 'https://www.libretrainsim.org/',
          icon: 'generic.png',
          pkgname: ['libre-trainsim-bin'],
        },
        {
          name: "Linley's Dungeon Crawl",
          description:
            'An open source roguelike adventure through dungeons filled with dangerous monsters in a quest to find the mystifyingly fabulous Orb of Zot.',
          url: 'http://www.dungeoncrawl.org/',
          icon: 'generic.png',
          pkgname: ['crawl'],
        },
        {
          name: 'Linux Air Combat',
          description:
            'Open source, multi-user 3D combat flight simulator featuring World War 2 aircraft. Supports joystick, gamepad, or mouse flight controls. .',
          url: 'https://sourceforge.net/projects/linuxaircombat//',
          icon: 'generic.png',
          pkgname: ['linux-air-combat'],
        },
        {
          name: 'Liquid War',
          description:
            '2D multiplayer game with a simple and unique game mechanic. It could be classified as a fast-paced strategy.',
          url: 'https://www.ufoot.org/liquidwar/',
          icon: 'generic.png',
          pkgname: ['liquidwar'],
        },
        {
          name: 'Lix',
          description:
            'Lemmings clone, i.e. assign roles to some of many constantly walking creatures to lead them safely through the exit.',
          url: 'http://www.lixgame.com/',
          icon: 'generic.png',
          pkgname: ['lix'],
        },
        {
          name: 'LPub3D',
          description: 'LDraw™ editor for LEGO® style digital building instructions.',
          url: 'https://trevorsandy.github.io/lpub3d',
          icon: 'generic.png',
          pkgname: ['lpub3d-appimage'],
        },
        {
          name: 'LTris',
          description: 'Arcade version of Tetris.',
          url: 'https://lgames.sourceforge.net/LTris/',
          icon: 'generic.png',
          pkgname: ['ltris'],
        },
        {
          name: 'Lure of the Temptress',
          description: 'fantasy point-and-click adventure game with comedic elements.',
          url: 'https://www.revolution.co.uk/games/lure/',
          icon: 'generic.png',
          pkgname: ['lure'],
        },
        {
          name: 'Mah-Jong',
          description: 'Chinese Classical mahjong (not solitaire) with network support.',
          url: 'https://mahjong.julianbradfield.org/',
          icon: 'generic.png',
          pkgname: ['mahjong'],
        },
        {
          name: 'Maniadrive',
          description: 'Arcade car game on acrobatic tracks with quick and nervous gameplay.',
          url: 'http://maniadrive.raydium.org/',
          icon: 'generic.png',
          pkgname: ['maniadrive'],
        },
        {
          name: 'Marvellous Inc.',
          description: 'MarvInc is a zachlike puzzle game with a story told through emails.',
          url: 'https://github.com/MarvellousSoft/MarvInc',
          icon: 'generic.png',
          pkgname: ['marvinc-git'],
        },
        {
          name: 'Micropolis',
          description: 'Open Source Micropolis, based on the original SimCity Classic from Maxis, by Will Wright.',
          url: 'https://github.com/simhacker/micropolis',
          icon: 'generic.png',
          pkgname: ['micropolis-git'],
        },
        {
          name: 'Moon Buggy',
          description: 'Simple game for the text mode.',
          url: 'https://www.seehuhn.de/pages/moon-buggy.html',
          icon: 'generic.png',
          pkgname: ['moon-buggy'],
        },
        {
          name: 'Naikari',
          description: 'Freeform 2-D space trading and mercenary game.',
          url: 'https://naikari.github.io/',
          icon: 'generic.png',
          pkgname: ['naikari'],
        },
        {
          name: 'Narcissu',
          description: 'Visual novel, telling the story of a terminally ill young man and woman.',
          url: 'http://narcissu.insani.org/',
          icon: 'generic.png',
          pkgname: ['narcissu2'],
        },
        {
          name: 'NetPanzer',
          description: 'An online multiplayer tactical warfare game designed for fast action combat.',
          url: 'https://github.com/netpanzer/netpanzer',
          icon: 'generic.png',
          pkgname: ['netpanzer-appimage'],
        },
        {
          name: 'Neverball',
          description: '3D game to guide a ball through a maze.',
          url: 'https://neverball.org/',
          icon: 'generic.png',
          pkgname: ['neverball'],
        },
        {
          name: 'Nikki and the Robots',
          description: 'Cute physics platformer.',
          url: 'https://github.com/nikki-and-the-robots/nikki',
          icon: 'generic.png',
          pkgname: ['nikki'],
        },
        {
          name: 'nInvaders',
          description: 'Ncurses based space invaders clone.',
          url: 'https://ninvaders.sourceforge.net/',
          icon: 'generic.png',
          pkgname: ['ninvaders'],
        },
        {
          name: 'Nootka',
          description: 'Application to learn classical score notation.',
          url: 'https://nootka.sourceforge.io/',
          icon: 'generic.png',
          pkgname: ['nootka'],
        },
        {
          name: 'Not Tetris 2',
          description: 'A Tetris-like game with realistic physics.',
          url: 'https://stabyourself.net/nottetris2/',
          icon: 'generic.png',
          pkgname: ['nottetris2'],
        },
        {
          name: 'nQuake',
          description:
            'Fast paced multiplayer FPS focusing on movement and trick jumps. This is the popular Quake / QuakeWorld package, including ezQuake client, 24bit textures, maps, bots and more. Can play on-line for free.',
          url: 'https://nquake.sourceforge.net/',
          icon: 'generic.png',
          pkgname: ['nquake'],
        },
        {
          name: 'nudoku',
          description: 'ncurses-based sudoku game',
          url: 'https://jubalh.github.io/nudoku/',
          icon: 'generic.png',
          pkgname: ['nudoku'],
        },
        {
          name: 'One Hour One Life',
          description: 'Binary package for One Hour One Life game by Jason Rohrer.',
          url: 'http://onehouronelife.com/',
          icon: 'generic.png',
          pkgname: ['onehouronelife-bin'],
        },
        {
          name: 'Oolite',
          description: '3D space trading and combat simulator in the spirit of Elite.',
          url: 'https://oolite.space/',
          icon: 'generic.png',
          pkgname: ['oolite'],
        },
        {
          name: 'openage',
          description: 'A free (as in freedom) clone of the Age of Empires II engine.',
          url: 'https://openage.sft.mx/',
          icon: 'generic.png',
          pkgname: ['openage-git'],
        },
        {
          name: 'OpenArena',
          description: 'Fast multiplayer shooter based on the quake3-engine.',
          url: 'http://openarena.ws',
          icon: 'generic.png',
          pkgname: ['openarena'],
        },
        {
          name: 'openblack',
          description: 'Open source reimplementation of the game Black & White (2001).',
          url: 'https://github.com/openblack/openblack',
          icon: 'generic.png',
          pkgname: ['openblack-git'],
        },
        {
          name: 'OpenClonk',
          description: 'Multiplayer-action-tactic-skill game.',
          url: 'https://www.openclonk.org/',
          icon: 'generic.png',
          pkgname: ['openclonk'],
        },
        {
          name: 'OpenDUNE',
          description: 'Open source re-creation of the popular game Dune II.',
          url: 'http://www.opendune.org/',
          icon: 'generic.png',
          pkgname: ['opendune'],
        },
        {
          name: 'OpenGothic',
          description: 'Open source remake of Gothic 2: Night of the raven',
          url: 'https://github.com/Try/OpenGothic',
          icon: 'generic.png',
          pkgname: ['opengothic'],
        },
        {
          name: 'OpenHV',
          description: 'Pixelart Science-Fiction Real-Time-Strategy game based on OpenRA.',
          url: 'https://www.openhv.net/',
          icon: 'generic.png',
          pkgname: ['openhv'],
        },
        {
          name: 'OpenLieroX',
          description: 'An extremely addictive real-time worms shoot-em-up backed by an active gamer community.',
          url: 'https://www.openlierox.net/',
          icon: 'generic.png',
          pkgname: ['openlierox'],
        },
        {
          name: 'OpenLoco',
          description: "An open source re-implementation of Chris Sawyer's Locomotion.",
          url: 'https://github.com/OpenLoco/OpenLoco',
          icon: 'generic.png',
          pkgname: ['openloco'],
        },
        {
          name: 'OpenXCom',
          description:
            'An open source implementation of the game UFO: Enemy Unknown (X-Com: UFO defence in North America), with a plethora of community created mods.',
          url: 'https://openxcom.org',
          icon: 'generic.png',
          pkgname: ['openxcom'],
        },
        {
          name: 'Orbiter 2016',
          description: 'Orbiter Space Flight Simulator.',
          url: 'http://orbit.medphys.ucl.ac.uk/index.html',
          icon: 'generic.png',
          pkgname: ['orbiter2016-git}}{{Broken package link'],
        },
        {
          name: 'osu!',
          description:
            'A free-to-win rhythm game with four game modes: osu!standard, a circle clicking simulator; osu!taiko, a drumming emulator; osu!catch, a fruit salad catcher; and osu!mania, a key smashing synthesizer.',
          url: 'https://osu.ppy.sh/',
          icon: 'generic.png',
          pkgname: ['osu}}, {{AUR'],
        },
        {
          name: 'Overte',
          description: 'Overte open source virtual worlds platform.',
          url: 'https://overte.org/',
          icon: 'generic.png',
          pkgname: ['overte-appimage'],
        },
        {
          name: 'Pasang Emas',
          description: 'Pasang-emas is a traditional two-player board game of Brunei.',
          url: 'https://pasang-emas.sourceforge.net/index.xhtml',
          icon: 'generic.png',
          pkgname: ['pasang-emas'],
        },
        {
          name: 'Penguin Command',
          description: 'Clone of the classic game "Missile Command" with improved graphics and sound.',
          url: 'https://www.linux-games.com/penguin-command/',
          icon: 'generic.png',
          pkgname: ['penguin-command'],
        },
        {
          name: 'Performous',
          description: 'An open-source karaoke, band and dancing game.',
          url: 'https://performous.org/',
          icon: 'generic.png',
          pkgname: ['performous-git'],
        },
        {
          name: 'Pinball',
          description: 'Open source pinball simulator for Linux and other Unix systems.',
          url: 'https://pinball.sourceforge.net/',
          icon: 'generic.png',
          pkgname: ['pinball'],
        },
        {
          name: 'Pioneers',
          description: 'A clone of the famous Settlers of Catan game with on-line functionality.',
          url: 'https://pio.sourceforge.net/',
          icon: 'generic.png',
          pkgname: ['pioneers'],
        },
        {
          name: 'Planeshift',
          description:
            'Role Playing Game immersed into a 3D virtual fantasy world which is FULLY FREE to play. Fully free means you will have no surprises of premium content which will limit your gameplay or unbalance the game. There are no limitations in skills, ranks, abilities, items you can gain with your free account.',
          url: 'https://www.planeshift.it',
          icon: 'generic.png',
          pkgname: ['planeshift-legacy'],
        },
        {
          name: 'Pokete',
          description: 'A small terminal based game in the style of a very popular and old game by Gamefreak.',
          url: 'https://lxgr-linux.github.io/pokete/',
          icon: 'generic.png',
          pkgname: ['pokete'],
        },
        {
          name: 'PowerManga',
          description: 'Arcade 2D shoot-em-up game with 41 levels and more than 200 sprites.',
          url: 'http://linux.tlk.fr/games/Powermanga/',
          icon: 'generic.png',
          pkgname: ['powermanga'],
        },
        {
          name: 'Prey',
          description: 'First Person Shooter released in 2006 (with a GNU/Linux port in 2008), published by 3D Realms.',
          url: 'https://www.3drealms.com/prey/index.html',
          icon: 'generic.png',
          pkgname: ['prey'],
        },
        {
          name: 'Principia',
          description: 'Physics-based sandbox building game.',
          url: 'https://principia-web.se/',
          icon: 'generic.png',
          pkgname: ['principia-git'],
        },
        {
          name: 'Project Outfox',
          description:
            'Generalist rhythm game engine. Started as a Stepmania fork, with the latest patches, classic OpenITG scripting support, and more. Currently supports 17 rhythm games style including dance, guitar, parapara, taiko, bongos, etc.',
          url: 'https://projectoutfox.com/',
          icon: 'generic.png',
          pkgname: ['outfox_bin'],
        },
        {
          name: 'Project Sushi',
          description: 'A short but challenging 2D platformer game.',
          url: 'https://www.patreon.com/posts/33983587',
          icon: 'generic.png',
          pkgname: ['project-sushi'],
        },
        {
          name: 'Q3Rally',
          description: 'A car driving and car combat game based on the Quake III Arena engine.',
          url: 'https://sourceforge.net/projects/q3rallysa/',
          icon: 'generic.png',
          pkgname: ['quake3-rally'],
        },
        {
          name: 'QCheckers',
          description: 'Qt-based checkers boardgame.',
          url: 'https://github.com/portnov/qcheckers',
          icon: 'generic.png',
          pkgname: ['qcheckers'],
        },
        {
          name: 'Quake 2',
          description: 'Built by Icculus.',
          url: 'https://www.icculus.org/quake2/',
          icon: 'generic.png',
          pkgname: ['quake2'],
        },
        {
          name: 'RBDOOM-3-BFG',
          description: 'Fork of Doom 3 BFG Edition.',
          url: 'https://github.com/RobertBeckebans/RBDOOM-3-BFG',
          icon: 'generic.png',
          pkgname: ['rbdoom-3-bfg'],
        },
        {
          name: 'Red Eclipse',
          description:
            'Single-player and multi-player first-person ego-shooter, built as a total conversion of Cube Engine 2.',
          url: 'https://redeclipse.net',
          icon: 'generic.png',
          pkgname: ['redeclipse'],
        },
        {
          name: 'Repixture',
          description:
            'Simplistic sandbox survival game that plays in mostly lush biomes in a mostly peaceful world and only simple technologies',
          url: 'https://content.luanti.org/packages/Wuzzy/repixture/',
          icon: 'generic.png',
          pkgname: ['minetest-repixture'],
        },
        {
          name: 'Ri-li',
          description: 'Toy wood engine GPL game.',
          url: 'https://ri-li.sourceforge.net/',
          icon: 'generic.png',
          pkgname: ['ri-li'],
        },
        {
          name: 'Rigs of Rods',
          description:
            'Sandbox-style vehicle simulator, the open-source predecessor to [https://www.beamng.com/ Beam.NG drive]. Features a realistic soft-body physics model, and an active modding community as of 2020.',
          url: 'https://www.rigsofrods.org/',
          icon: 'generic.png',
          pkgname: ['rigsofrods'],
        },
        {
          name: 'Rigs of Rods',
          description:
            'Sandbox-style vehicle simulator, the open-source predecessor to [https://www.beamng.com/ Beam.NG drive]. Features a realistic soft-body physics model, and an active modding community as of 2020.',
          url: 'https://www.rigsofrods.org/',
          icon: 'generic.png',
          pkgname: ['rigsofrods'],
        },
        {
          name: 'Rogue',
          description: 'Original dungeon crawl game.',
          url: 'http://rogue.rogueforge.net/rogue-5-4/',
          icon: 'generic.png',
          pkgname: ['rogue'],
        },
        {
          name: 'Rune',
          description: "3rd person Adventure / Hack'n Slay using Unreal Engine. Runs great from box installation.",
          url: 'http://www.rune-world.com',
          icon: 'generic.png',
          pkgname: ['rune'],
        },
        {
          name: 'RuneScape',
          description: 'Massive online adventure game by Jagex.',
          url: 'https://www.runescape.com',
          icon: 'generic.png',
          pkgname: ['bolt-launcher}} (unofficial Jagex Launcher), {{AUR'],
        },
        {
          name: 'Ryzom',
          description: '3D Fantasy MMORPG.',
          url: 'https://www.ryzom.com',
          icon: 'generic.png',
          pkgname: ['ryzom-client-git'],
        },
        {
          name: 'S.U.A.V.E.',
          description:
            'fun racing game, where you drive very small, but very brave tank! This tank is equipped by modern heavy weapon, which strikes the rivals in different distances!',
          url: 'https://archive.org/details/Sport-Utility_Assault_Vehicle_Extreme',
          icon: 'generic.png',
          pkgname: ['suave'],
        },
        {
          name: 'Sabaki',
          description: 'An elegant Go board and SGF editor for a more civilized age.',
          url: 'https://github.com/SabakiHQ/Sabaki',
          icon: 'generic.png',
          pkgname: ['sabaki'],
        },
        {
          name: 'Savage 2: A Tortured Soul',
          description:
            'Fantasy themed online multiplayer team-based FPS/RTS/RPG hybrid. Free-to-play as of December 2008. Pay for premium accounts providing crucial game elements such as extra inventory slots, access to clans and removal of the Hellbourne unit restrictions (per-account), as well as access to replays and stats.',
          url: 'https://savage2.net/',
          icon: 'generic.png',
          pkgname: ['savage2'],
        },
        {
          name: 'School Days',
          description:
            'The story, a dramatic slice-of-life, follows Makoto Ito, a high school student who becomes the ambivalent love interest of several girls during his second term, and the effects this has on himself and his relationships with other characters.',
          url: 'https://schooldays.us/',
          icon: 'generic.png',
          pkgname: ['nice-boat'],
        },
        {
          name: 'Scidb',
          description:
            'Chess database browser: includes engines for chess, chess960, etc; import from PGN, Scid, Chessbase, etc; CQL++ searching.',
          url: 'https://sourceforge.net/projects/scidb/',
          icon: 'generic.png',
          pkgname: ['scidb-svn'],
        },
        {
          name: 'Secret Maryo Chronicles',
          description: 'Mario-style game.',
          url: 'http://www.secretmaryo.org/',
          icon: 'generic.png',
          pkgname: ['smc'],
        },
        {
          name: 'Serious Sam: The First Encounter',
          description:
            'Open source game engine version developed by Croteam for Serious Sam Classic with Vulkan support.',
          url: 'https://github.com/tx00100xt/SeriousSamClassic-VK',
          icon: 'generic.png',
          pkgname: ['serioussam-vk'],
        },
        {
          name: 'Serious Sam: The Second Encounter',
          description:
            'Open source game engine version developed by Croteam for Serious Sam Classic with Vulkan support.',
          url: 'https://github.com/tx00100xt/SeriousSamClassic-VK',
          icon: 'generic.png',
          pkgname: ['serioussam-vk'],
        },
        {
          name: 'Seven Kingdoms Ancient Adversaries',
          description:
            'Conquer the world and build your empire! Lead one civilization to glory through sophisticated trade, diplomacy, espionage and conquest',
          url: 'https://7kfans.com/',
          icon: 'generic.png',
          pkgname: ['7kaa'],
        },
        {
          name: 'Shadow Of The Wyrm',
          description: 'is a single player, traditional roguelike by Julian Day.',
          url: 'https://www.shadowofthewyrm.org',
          icon: 'generic.png',
          pkgname: ['sotw'],
        },
        {
          name: 'Signus',
          description:
            "''Signus: The Artefact Wars'' classic turn-based strategy war game similar to the old ''Battle Isle'' series.",
          url: 'https://github.com/signus-game/signus/',
          icon: 'generic.png',
          pkgname: ['signus'],
        },
        {
          name: 'Space Station 14',
          description:
            'A multiplayer game about paranoia and chaos on a space station. Remake of the cult-classic Space Station 13',
          url: 'https://spacestation14.io/',
          icon: 'generic.png',
          pkgname: ['spacestation14-launcher-bin'],
        },
        {
          name: 'Speed Dreams',
          description: 'Fork of Torcs, aiming to implement exciting new features as well as improving realism.',
          url: 'http://speed-dreams.org/',
          icon: 'generic.png',
          pkgname: ['speed-dreams-appimage'],
        },
        {
          name: 'Stendhal',
          description: 'Stendhal is a fun friendly and free multiplayer online adventure game with an old school feel.',
          url: 'https://www.stendhalgame.org/',
          icon: 'generic.png',
          pkgname: ['stendhal-bin'],
        },
        {
          name: 'Stepmania',
          description: 'Advanced dance simulation game.',
          url: 'https://www.stepmania.com/',
          icon: 'generic.png',
          pkgname: ['stepmania'],
        },
        {
          name: 'Streets of Rage Remake',
          description: 'A remake of the classic Streets of Rage 1, 2 and 3 by Sega.',
          url: 'https://sorr.forumotion.net/',
          icon: 'generic.png',
          pkgname: ['streetsofrageremake'],
        },
        {
          name: 'Stunt Rally',
          description: 'Racing game with rally style of driving, mostly on gravel.',
          url: 'https://stuntrally.tuxfamily.org/',
          icon: 'generic.png',
          pkgname: ['stuntrally-git'],
        },
        {
          name: 'Sulis',
          description: 'Turn based tactical RPG with several campaigns, written in Rust.',
          url: 'https://www.sulisgame.com/',
          icon: 'generic.png',
          pkgname: ['sulis'],
        },
        {
          name: 'Summer Days',
          description: 'Spin-off from the "Days" series and remake of Summer Days.',
          url: 'https://shinydays.us/',
          icon: 'generic.png',
          pkgname: ['nice-boat'],
        },
        {
          name: 'TADS',
          description:
            'Prototype-based domain-specific programming language and set of standard libraries for creating interactive fiction (IF) games.',
          url: 'https://tads.org',
          icon: 'generic.png',
          pkgname: ['frobtads'],
        },
        {
          name: "Tales of Maj'Eyal (previously ''Troubles of Middle Earth'')",
          description: 'A dungeon crawler similar to Angband, based on the works of Tolkien.',
          url: 'https://te4.org/',
          icon: 'generic.png',
          pkgname: ['tome4'],
        },
        {
          name: 'Tecnoballz',
          description: 'An exciting brick breaker game.',
          url: 'https://linux.tlk.fr/games/TecnoballZ/',
          icon: 'generic.png',
          pkgname: ['tecnoballz'],
        },
        {
          name: 'Tesseract',
          description: 'Smooth FPS with map editing, instagib, DM and CTF.',
          url: 'http://tesseract.gg/',
          icon: 'generic.png',
          pkgname: ['tesseract-game'],
        },
        {
          name: 'Tetrinet',
          description: 'Multiplayer online Tetris game for up to six people.',
          url: 'https://gtetrinet.sourceforge.net/',
          icon: 'generic.png',
          pkgname: ['gtetrinet'],
        },
        {
          name: 'The Legend of Edgar',
          description:
            '2D platformer: Venture across the world, battle fearsome creatures and solve puzzles to rescue your father.',
          url: 'https://www.parallelrealities.co.uk/games/edgar/',
          icon: 'generic.png',
          pkgname: ['legendofedgar'],
        },
        {
          name: 'The Mana World',
          description: 'Serious effort to create an innovative free and open source MMORPG.',
          url: 'https://www.themanaworld.org',
          icon: 'generic.png',
          pkgname: ['manaplus'],
        },
        {
          name: 'The Powder Toy',
          description:
            'Open source physics sandbox game, which simulates air pressure and velocity, heat, gravity and a countless number of interactions between different substances.',
          url: 'https://powdertoy.co.uk/',
          icon: 'generic.png',
          pkgname: ['powder-toy'],
        },
        {
          name: 'Thrive',
          description:
            'Game about evolution, in which the player guides a species from their origin as a microbe to the space age and beyond.',
          url: 'https://revolutionarygamesstudio.com/',
          icon: 'generic.png',
          pkgname: ['thrive-bin'],
        },
        {
          name: 'Toppler',
          description: 'Reimplementation of the classic jump & run game "Nebulus".',
          url: 'https://gitlab.com/roever/toppler/',
          icon: 'generic.png',
          pkgname: ['toppler'],
        },
        {
          name: 'Torcs',
          description: '3D racing cars simulator using OpenGL.',
          url: 'https://torcs.sourceforge.net/',
          icon: 'generic.png',
          pkgname: ['torcs'],
        },
        {
          name: 'Trackballs',
          description: 'A 3D marble game inspired by the classic Marble Madness.',
          url: 'https://trackballs.github.io/',
          icon: 'generic.png',
          pkgname: ['trackballs'],
        },
        {
          name: 'Tremulous',
          description: 'FPS with elements of real time strategy, featuring humans and aliens.',
          url: 'https://github.com/grangerhub/tremulous/',
          icon: 'generic.png',
          pkgname: ['tremulous-grangerhub-bin'],
        },
        {
          name: 'Trigger Rally',
          description: 'Free OpenGL rally car racing game.',
          url: 'https://sourceforge.net/projects/trigger-rally/',
          icon: 'generic.png',
          pkgname: ['trigger'],
        },
        {
          name: 'TripleA',
          description: 'An online multiplayer turn based strategy game and board game engine.',
          url: 'https://triplea-game.org/',
          icon: 'generic.png',
          pkgname: ['triplea'],
        },
        {
          name: 'Tux Math',
          description: 'Arcade game that helps kids practice their math facts.',
          url: 'https://github.com/tux4kids/tuxmath',
          icon: 'generic.png',
          pkgname: ['tuxmath'],
        },
        {
          name: 'Tux Paint',
          description: 'Drawing program designed for young children.',
          url: 'https://tuxpaint.org/',
          icon: 'generic.png',
          pkgname: ['tuxpaint'],
        },
        {
          name: 'Tux Typing',
          description: 'Educational typing tutor for kids starring Tux.',
          url: 'https://github.com/tux4kids/tuxtype',
          icon: 'generic.png',
          pkgname: ['tuxtype'],
        },
        {
          name: 'Tuxemon',
          description: 'A free, open source monster-fighting RPG.',
          url: 'https://www.tuxemon.org/',
          icon: 'generic.png',
          pkgname: ['tuxemon-git}}{{Broken package link'],
        },
        {
          name: 'Ultimate Stunts',
          description: "Remake of the famous DOS-game 'stunts'.",
          url: 'http://www.ultimatestunts.nl/',
          icon: 'generic.png',
          pkgname: ['ultimatestunts'],
        },
        {
          name: 'Ultrastar Deluxe',
          description: 'A SingStar karaoke clone.',
          url: 'https://usdx.eu/',
          icon: 'generic.png',
          pkgname: ['ultrastardx-git'],
        },
        {
          name: 'Unknown Horizons',
          description:
            '2.5D isometric real-time strategy simulation with an emphasis on economy and city building. Expand your small settlement to a strong and wealthy colony, collect taxes and supply your inhabitants with valuable goods. Increase your power with a well balanced economy and with strategic trade and diplomacy.',
          url: 'http://www.unknown-horizons.org/',
          icon: 'generic.png',
          pkgname: ['unknown-horizons'],
        },
        {
          name: 'Unreal Tournament (2014)',
          description: 'Free and open-source remake of the original using Unreal Engine 4.',
          url: 'https://www.unrealtournament.com/',
          icon: 'generic.png',
          pkgname: ['unrealtournament4'],
        },
        {
          name: 'Unvanquished',
          description:
            'Team-based fps/rts hybrid game which pits aliens against humans. Monthly release that can be played on official servers.',
          url: 'https://unvanquished.net/',
          icon: 'generic.png',
          pkgname: ['unvanquished'],
        },
        {
          name: 'Urban Terror',
          description: 'Modern multiplayer FPS based on the ioquake3 engine.',
          url: 'http://urbanterror.info',
          icon: 'generic.png',
          pkgname: ['urbanterror'],
        },
        {
          name: 'Valyria Tear',
          description: 'An attempt at creating a free (as meant in the Gnu Public License) J-RPG game.',
          url: 'https://valyriatear.blogspot.com/',
          icon: 'generic.png',
          pkgname: ['valyria-tear-git'],
        },
        {
          name: 'VDrift',
          description: 'Open source driving simulation made with drift racing in mind.',
          url: 'https://vdrift.net/',
          icon: 'generic.png',
          pkgname: ['vdrift'],
        },
        {
          name: 'Vega Strike',
          description: 'Realistic space flight simulator with trading and fighting.',
          url: 'https://www.vega-strike.org',
          icon: 'generic.png',
          pkgname: ['vegastrike'],
        },
        {
          name: 'Vintage Story',
          description: 'An in-development indie sandbox game about innovation and exploration.',
          url: 'https://www.vintagestory.at/',
          icon: 'generic.png',
          pkgname: ['vintagestory'],
        },
        {
          name: 'Voxelands',
          description: 'A fork of Minetest, an Infiniminer/Minecraft inspired game.',
          url: 'https://gitlab.com/voxelands/voxelands',
          icon: 'generic.png',
          pkgname: ['voxelands'],
        },
        {
          name: 'VoxeLibre',
          description: 'Minecraft clone game for Luanti.',
          url: 'https://git.minetest.land/VoxeLibre/VoxeLibre',
          icon: 'generic.png',
          pkgname: ['luanti-voxelibre'],
        },
        {
          name: 'vpinball',
          description: 'An open source pinball table editor and simulator',
          url: 'https://github.com/vpinball/vpinball',
          icon: 'generic.png',
          pkgname: ['vpinball'],
        },
        {
          name: 'VVVVVV',
          description:
            'Highly praised 2D puzzle platform indie game with a C64 retro theme, with a great chiptune soundtrack.',
          url: 'https://thelettervsixtim.es/',
          icon: 'generic.png',
          pkgname: ['vvvvvv-git'],
        },
        {
          name: 'wanderer',
          description: 'Wanderer is a game similar to Boulderdash, Repton, XOR and others.',
          url: 'https://e271.net/~marina/wanderer.html',
          icon: 'generic.png',
          pkgname: ['wanderer'],
        },
        {
          name: "Warmux (previously ''Wormux'')",
          description: 'Somewhat similar to Worms 2/Worms Armageddon.',
          url: 'https://github.com/a-team/wormux/',
          icon: 'generic.png',
          pkgname: ['warmux'],
        },
        {
          name: 'WolkenWelten',
          description: 'Gamemix between Minecraft, Quake ]I[ and Emacs in C99.',
          url: 'https://wolkenwelten.net/',
          icon: 'generic.png',
          pkgname: ['wolkenwelten-git'],
        },
        {
          name: 'World of Goo',
          description: 'Great 2D puzzle game.',
          url: 'https://www.2dboy.com',
          icon: 'generic.png',
          pkgname: ['worldofgoo'],
        },
        {
          name: 'World of Padman',
          description: 'Stand slone somplex &ndash; cartoon-style multiplayer first-person shooter.',
          url: 'https://worldofpadman.net/website',
          icon: 'generic.png',
          pkgname: ['worldofpadman'],
        },
        {
          name: 'Wrymsun',
          description: 'Fantasy game initially based on Stratagus engine.',
          url: 'https://andrettin.github.io/',
          icon: 'generic.png',
          pkgname: ['Wyrmsun'],
        },
        {
          name: 'XBill',
          description:
            'Kill all instances of a virus before it infects all computers with a malware resembling Microsoft Windows.',
          url: 'http://www.xbill.org/',
          icon: 'generic.png',
          pkgname: ['xbill'],
        },
        {
          name: 'XInvaders3D',
          description: 'XInvaders3D is a 3D Vector Graphics Space Invaders clone for X11.',
          url: 'https://github.com/JoesCat/xinvaders3d',
          icon: 'generic.png',
          pkgname: ['xinvaders3d'],
        },
        {
          name: 'XMoto',
          description: 'Challenging 2D motocross platform game, where physics play an important role.',
          url: 'https://xmoto.tuxfamily.org/',
          icon: 'generic.png',
          pkgname: ['xmoto'],
        },
        {
          name: 'XPilot',
          description:
            'XPilot is a multi-player 2D space game. Some features are borrowed from classics like the Atari coin-ups Asteroids and Gravitar, and the home-computer games Thrust (Commodore 64) and Gravity Force (Commodore Amiga), but XPilot has many new aspects too.',
          url: 'https://www.xpilot.org/',
          icon: 'generic.png',
          pkgname: ['xpilot'],
        },
        {
          name: 'xroach',
          description: 'cockroaches hide under your windows.',
          url: 'https://github.com/sergev/4.4BSD-Lite2/tree/master/usr/src/games/xroach',
          icon: 'generic.png',
          pkgname: ['xroach'],
        },
        {
          name: 'Xscorch',
          description: 'Clone of the classic DOS game Scorched Earth.',
          url: 'http://www.xscorch.org/',
          icon: 'generic.png',
          pkgname: ['xscorch'],
        },
        {
          name: 'xu4',
          description: 'Remake of the computer game Ultima IV.',
          url: 'https://xu4.sourceforge.net/',
          icon: 'generic.png',
          pkgname: ['xu4-svn'],
        },
        {
          name: 'ZDoom',
          description: 'Enhanced Doom port with additional support for Heretic, Hexen and Strife.',
          url: 'https://www.zdoom.org/',
          icon: 'generic.png',
          pkgname: ['zdoom'],
        },
        {
          name: 'Zero-K',
          description: 'Open source RTS game running on the Spring engine .',
          url: 'https://zerok.itch.io/zero-k',
          icon: 'generic.png',
          pkgname: ['zero-k'],
        },
      ],
    },
    {
      name: 'gaming.emulators',
      sections: [
        { name: 'DGen/SDL', pkgname: ['dgen-sdl'], icon: 'dgen.png' },
        { name: 'DOSBox', pkgname: ['dosbox'], icon: 'DOSBox.png' },
        { name: 'Desmume', pkgname: ['desmume'], icon: 'desmume.png' },
        { name: 'Dolphin', pkgname: ['dolphin-emu'], icon: 'dolphin-emu.png' },
        { name: 'Dolphin-emu', pkgname: ['dolphin-emu'], icon: 'dolphin-emu.png' },
        { name: 'DuckStation', pkgname: ['duckstation'], icon: 'duckstation.png' },
        { name: 'Emulationstation', pkgname: ['emulationstation'], icon: 'es-0.png' },
        { name: 'FCEUX', pkgname: ['fceux'], icon: 'fceux.png' },
        { name: 'FS-UAE', pkgname: ['fs-uae'], icon: 'fs-uae.png' },
        { name: 'Hatari', pkgname: ['hatari'], icon: 'hatari.png' },
        { name: 'Higan', pkgname: ['higan'], icon: 'higan.png' },
        { name: 'Kega Fusion', pkgname: ['kega-fusion'], icon: 'kega-fusion.png' },
        { name: 'Libretro (all cores)', pkgname: ['libretro-meta'], icon: 'libretro.png' },
        { name: 'Libretro', pkgname: ['libretro'], icon: 'libretro.png' },
        { name: 'MAME', pkgname: ['mame'], icon: 'generic.png' },
        { name: 'Mandarine (Citra)', pkgname: ['mandarine-git'], icon: 'mandarine.svg' },
        { name: 'Mednafen', pkgname: ['mednafen'], icon: 'generic.png' },
        { name: 'Nestopia', pkgname: ['nestopia'], icon: 'nestopia.png' },
        { name: 'PCSX-R', pkgname: ['pcsxr'], icon: 'pcsxr.png' },
        { name: 'PCSX2', pkgname: ['pcsx2'], icon: 'pcsx2.png' },
        { name: 'PPSSPP', pkgname: ['ppsspp'], icon: 'ppsspp.png' },
        { name: 'Pegasus frontend', pkgname: ['pegasus-frontend-git'], icon: 'generic.png' },
        { name: 'RPCS3', pkgname: ['rpcs3'], icon: 'rpcs3.png' },
        { name: 'Reicast', pkgname: ['reicast'], icon: 'reicast.png' },
        { name: 'RyuJinx', pkgname: ['ryujinx'], icon: 'ryujinx.png' },
        { name: 'SameBoy', pkgname: ['sameboy'], icon: 'sameboy.png' },
        { name: 'ScummVM', pkgname: ['scummvm'], icon: 'scummvm.png' },
        { name: 'Snes9x', pkgname: ['snes9x'], icon: 'snes9x.png' },
        { name: 'Stella', pkgname: ['stella'], icon: 'stella.gif' },
        { name: 'Torzu (Yuzu)', pkgname: ['torzu-qt6-git'], icon: 'torzu.png' },
        { name: 'VBA-M', pkgname: ['vbam-wx'], icon: 'vba-m.png' },
        { name: 'VICE', pkgname: ['vice'], icon: 'vice.svg' },
        { name: 'WayDroid', pkgname: ['waydroid-script-git'], icon: 'waydroid.png' },
        { name: 'Xemu', pkgname: ['xemu'], icon: 'xemu.png' },
        { name: 'Yabause', pkgname: ['yabause-qt'], icon: 'yabause.png' },
        { name: 'ZSNES', pkgname: ['zsnes'], icon: 'zsnes.png' },
        { name: 'ePSXe', pkgname: ['epsxe'], icon: 'epsxe.png' },
        { name: 'eka2l1', pkgname: ['eka2l1-git'], icon: 'eka2l1.png' },
        { name: 'mGBA', pkgname: ['mgba'], icon: 'mgba.png' },
        { name: 'mupen64plus', pkgname: ['m64py'], icon: 'mupen64plus.png' },
      ],
    },
  ];

  protected readonly operationManager = inject(OperationManagerService);
  private readonly configService = inject(ConfigService);
  private readonly logger = Logger.getInstance();
  private readonly loadingService = inject(LoadingService);

  constructor() {
    effect(() => {
      const darkMode = this.configService.settings().darkMode;
      this.backgroundColor.set(darkMode ? flavors.mocha.colors.surface0.hex : flavors.latte.colors.surface0.hex);
    });
  }

  async ngOnInit(): Promise<void> {
    this.loadingService.loadingOn();
    await this.checkInstalled();
    this.loadingService.loadingOff();
  }

  async checkInstalled() {
    this.logger.info('Checking installed packages');
    const cmd = 'pacman -Qq';
    const result: ChildProcess<string> = await Command.create('exec-bash', ['-c', cmd]).execute();

    if (result.code !== 0) {
      this.logger.error(`Error checking installed packages: ${result.stderr}`);
      return;
    }

    const installedPackages: string[] = result.stdout.split('\n');
    for (const sections of this.data) {
      for (const pkg of sections.sections) {
        pkg.selected = installedPackages.includes(pkg.pkgname[0]);
        pkg.initialState = pkg.selected;
      }
    }
  }

  togglePackage(item: StatefulPackage): void {
    item.selected = !item.selected;
    this.operationManager.handleTogglePackage(item);
  }
}
