stages:
  - build
  - publish

build_linux:
  image: node:22-slim
  stage: build
  script:
    - apt-get update
    - |
      DEBIAN_FRONTEND=noninteractive apt-get install -y \
        libwebkit2gtk-4.1-dev \
        build-essential \
        curl \
        wget \
        file \
        libxdo-dev \
        libssl-dev \
        libayatana-appindicator3-dev \
        librsvg2-dev \
        libsoup-3.0-0
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain stable -y
    - source "$HOME/.cargo/env"
    - corepack enable pnpm
    - pnpm install
    - pnpm run tauri build
  artifacts:
    when: on_success
    access: all
    expire_in: '30 days'
    paths:
      - src-tauri/target/release/bundle
